service: function-example-aws

provider:
  name: aws
  runtime: java8
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${opt:profile, self:custom.defaultProfile}
  region: ${opt:region, self:custom.defaultRegion}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:UpdateItem"
      Resource: "*"
  memorySize: 1024
  timeout: 30

custom:
  defaultStage: staging
  defaultProfile: default
  defaultRegion: ap-northeast-1

plugins:
  - serverless-prune-plugin

package:
  artifact: target/function-example-1.0.0-aws.jar

functions:
  CountUp:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootApiGatewayRequestHandler
    environment:
      FUNCTION_NAME: countUp
    events:
      - http:
          path: countUp
          method: post
          integration: lambda-proxy
  CountUpFlux:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootApiGatewayRequestHandler
    environment:
      FUNCTION_NAME: countUpFlux
    events:
      - http:
          path: countUpFlux
          method: post
          integration: lambda-proxy
  Dispatch:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootApiGatewayRequestHandler
    environment:
      FUNCTION_NAME: dispatch
      ECHO_URI:
        Fn::Join:
          - ""
          - ["https://", { Ref: "ApiGatewayRestApi" }, ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}/echo" ]
    events:
      - http:
          path: dispatch
          method: post
          integration: lambda-proxy
  DispatchFlux:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootApiGatewayRequestHandler
    environment:
      FUNCTION_NAME: dispatchFlux
      ECHO_FLUX_URI:
        Fn::Join:
            - ""
            - ["https://", { Ref: "ApiGatewayRestApi" }, ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}/echoFlux" ]
    events:
      - http:
          path: dispatchFlux
          method: post
          integration: lambda-proxy
  Echo:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootApiGatewayRequestHandler
    environment:
      FUNCTION_NAME: echo
    events:
      - http:
          path: echo
          method: post
          integration: lambda-proxy
  EchoFlux:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootApiGatewayRequestHandler
    environment:
      FUNCTION_NAME: echoFlux
    events:
      - http:
          path: echoFlux
          method: post
          integration: lambda-proxy

resources:
  Resources:
    CounterTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userName
            AttributeType: S
        KeySchema:
          - AttributeName: userName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 2
        TableName: counter

    CountUpLogGroup:
      Properties:
        RetentionInDays: 3
    CountUpFluxLogGroup:
      Properties:
        RetentionInDays: 3
    DispatchLogGroup:
      Properties:
        RetentionInDays: 3
    DispatchFluxLogGroup:
      Properties:
        RetentionInDays: 3
    EchoLogGroup:
      Properties:
        RetentionInDays: 3
    EchoFluxLogGroup:
      Properties:
        RetentionInDays: 3
